frog:
  game_title: 'Frog'
  screen: None
  screen_width: 1280  
  screen_height: 960
  frame_rate: 60
  clock: None
  jump: False
  drop: False
  left: False
  right: False
  drop_rate: 4
  gravity: -20
  bg_music:
  bg_music_volume:
  road_noise_fpath: 'sounds/road-noise.wav'
  road_noise_volume: 0.7
  water_noise_fpath: 
  water_noise_volume: 0.6
  images: 
    - name: 'background'
      fpath: 'images/background.png'
      sound:
        fpath: 
        volume: 0.5
        fx: None
      start: 
          x: 0
          y: 0 
      coord: 
          x: 0
          y: 0 
      surface: None 
      rect: None
      speed: 0
      gravity: 0
    - name: 'frog'
      fpath: 'images/frog.png'
      sound:
        fpath: 'sounds/frog-jump01.mp3'
        volume: 0.5
        fx: None
      start: 
          x: 640
          y: 880
      coord: 
          x: 640
          y: 880
      surface: None 
      rect: None
      speed: 4
      gravity: -20
    - name: 'log'
      fpath: 'images/log.png'
      sound:
        fpath:
        volume: 0.5
        fx: None
      start: 
          x: 640
          y: 300
      coord: 
          x: 640
          y: 300
      surface: None 
      rect: None
      speed: 8
      gravity: 0 # doesn't move on y axis
    - name: 'car'
      fpath: 'images/car.png'
      sound:
        fpath: 
        volume: 0.5
        fx: None
      start: 
          x: 640
          y: 600
      coord: 
          x: 640
          y: 600
      surface: None 
      rect: None
      speed: 8
      gravity: 0 # doesn't move on y axis
  