frog:
  game_title: 'Frog'
  screen: 
  screen_width: 1280  
  screen_height: 960
  frame_rate: 60
  fade_rate: 10
  fade_size: 0
  hits: 0
  small_text:
    size: 20
    style: 'Lucida Sans'
    font:
  large_text:
    size: 24
    style: 'Lucida Sans'
    font:
  score:
    current: 0
    highest: 0
    fpath: 'scores.txt'
    status:
  clock: 
  jump:
  back:
  left:
  right:
  up:
  bg_music:
  bg_music_volume:
  road_noise_fpath: 'sounds/road-noise.wav'
  road_noise_volume: 0.7
  water_noise_fpath: 
  water_noise_volume: 0.6
  max_frogs_speed: 10
  min_frogs_speed: 2
  max_cars_speed: 10
  min_cars_speed: 2
  max_logs_speed: 12
  min_logs_speed: 3
  backgrounds:
      fpath: 'images/background*.png'
      filename:
      name:
      visible: True
      sound:
        fpath: 'sounds/road-noise.wav'
        volume: 0.5
        fx:
      base: 
          start: 940
          end: 860
          sound:
            fpath: 'sounds/road-noise.wav'
            volume: 0.5
            fx:
      road:
          start: 810
          end: 470
          sound:
            fpath: 'sounds/road-noise.wav'
            volume: 0.5
            fx:
      water:
          start: 425
          end: 50
          sound:
            fpath: 'sounds/road-noise.wav'
            volume: 0.5
            fx:
      surface:
      speed:
      rect:
  frogs: 
      fpath: 'images/frog*.png'
      name:
      filename:
      visible: True
      sound:
        fpath: 'sounds/frog-jump01.mp3'
        volume: 0.5
        fx:
      surface: 
      rect: 
      speed: 40
      jump: 40
  logs:
      fpath: 'images/log*.png'
      filename:
      name:
      visible: True
      sound:
        fpath: 'sounds/road-noise.wav'
        volume: 0.5
        fx:
      miss:
        sound:
          fpath: 'sounds/watery-splash.wav'
          volume: 0.5
          fx: 
        image:
          fpath: 'images/ouch64.png'
          surface:
          rect:
      surface:
      rect:
      speed: 8
  cars:
      fpath: 'images/car*.png'
      filename:
      name:
      visible: True
      sound:
        fpath: 'sounds/road-noise.wav'
        volume: 0.5
        fx:
      crash:
        sound:
          fpath: 'sounds/car-crash.mp3'
          volume: 0.5
          fx: 
        image:
          fpath: 'images/ouch64.png'
          surface:
          rect:
      surface:
      rect:
      speed: 8
  objects: 
    backgrounds:
    frogs:
    cars: 
    logs: 