GAME_TITLE = 'frogger'

SCREEN_WIDTH = 1280  
SCREEN_HEIGHT = 960
FRAME_RATE = 60

BASE_START = 940
BASE_END = 860
ROAD_START = 810
ROAD_END = 470
WATER_START = 425
WATER_END = 50

NUM_BACKGROUNDS = 1
BACKGROUND_IMAGE_FPATH = 'images/background.png'

NUM_FROGS = 1
FROG_JUMP_SPEED = 6
FROG_MOVE_SPEED = 6
FROG_IMAGE_FPATH = 'images/frog.png'
FROG_JUMP_SOUND = 'sounds/frog-jump01.mp3'

NUM_CARS = 10
CAR_SPAWN_RATE = 500
CAR_MAX_SPEED = 6
CAR_MIN_SPEED = 1
CAR_IMAGE_FPATH = 'images/car.png'
CAR_CRASH_FPATH = 'images/ouch48.png'
CAR_CRASH_SOUND = 'sounds/car-crash.mp3'
CAR_CRASH_VOLUME = 0.5

NUM_LOGS = 10
LOG_MIN_SPEED = 1
LOG_MAX_SPEED = 4
LOG_IMAGE_FPATH = 'images/log.png'
LOG_JUMP_SOUND = 'sounds/frog-jump01.mp3'

LARGE_TEXT_SIZE = 24
LARGE_TEXT_FONT = 'Lucida Sans'

SMALL_TEXT_SIZE = 20
SMALL_TEXT_FONT = 'Lucida Sans'
